### PR TITLE
Add support for Neos Leak Sensors

### PR DESCRIPTION
**Pull request by dale3h**
**Extensive user testing should be completed before this PR is merged.**

Add support for Neos Leak Sensors.

Credit to @jellybob.

This PR addresses #29.

### CODE REVIEW

**Comment by raetha** [comment]
This looks to cover the WyzeSensePy fork part of this, but still need some changes to the WS2MQTT code to properly recognize and handle these. Also want to make sure that any new sensors of this type have the invert_sensor state set correctly. I'll do a more thorough review as soon as I can.

@dale3h Nice job jumping on this and some of the other open issues/features!

**Comment by dale3h** [comment]
@raetha Please review the latest changes and see if these are satisfactory for the WS2MQTT code side of things for this feature.

Also, thank you for your kind words. Happy to help when and where I can!

**Comment by dale3h** [comment]
After reading more on #29, more work will be necessary to integrate temperature. I will try to check the original code tomorrow and see if I can integrate the temperature sensor as well.

**Comment by raetha** [comment]
@dale3h since temperature appears to be a different event_type, we need to determine what triggers that event, as with a different event type, I'm thinking it may not be a simple state change, but triggered on something. I'll pose this to @jellybob in the other thread.

**Pull request merged**
