### PR TITLE
Add V2 Motion and  Contact Sensor support

### PR DESCRIPTION
**Pull request by AK5nowman**
This does not support the keypad. A new firmware needs to be flashed to the Wyze V1 dongle in order to receive keypad events.

### CODE REVIEW

**Comment by drinfernoo** [comment]
One thing I noticed here is that (even though the sensors are now working) `device_class` is still returning as `null`...
```json
{
  "event": "alarm",
  "available": true,
  "mac": "77C00CE1",
  "device_class": null,
  "last_seen": 1620923753.433,
  "last_seen_iso": "2021-05-13T09:35:53.433000",
  "signal_strength": -22,
  "battery": 103,
  "name": "Back Porch Motion",
  "state": 0
}
```

**Comment by drinfernoo** [comment]
Aha! Fixed the `device_class` issue here: https://github.com/AK5nowman/wyzesense2mqtt/pull/1

**Review by raetha — APPROVED** [review]
Changes look good approving merge.

**Comment by drinfernoo** [comment]
@raetha Will this 2.0 tag be available as a Docker image?

**Pull request merged**
